name: Template Smoke Test

on: [push, pull_request]

jobs:
  test-template:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install copier
        run: pip install copier
      - name: Smoke test template generation
        run: |
          copier copy . ./test-output --force --defaults --trust
          echo "Template generated successfully."
          # Add basic checks here, e.g., check if key files exist
          test -f ./test-output/README.md || (echo "README.md not found" && exit 1)
          test -f ./test-output/src/my_new_project/__init__.py || (echo "__init__.py not found" && exit 1)
